name: static_site
namespace: default
replicas: 1
service:
  ports:
  - protocol: TCP
    port: 80
deployment:
  template:
    annotations: {}
  containers:
    imagePullPolicy: "IfNotPresent"
    resources:
      requests:
        memory: "150Mi"
        cpu: "0.2"
        ephemeral_storage: "500Mi"
      limits:
        memory: "300Mi"
        cpu: "0.4"
        ephemeral_storage: "500Mi"
    lifecycle: ""
    ports:
    - name: http
      containerPort: 80
    readinessProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    livenessProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      initialDelaySeconds: 30
      periodSeconds: 5
    startupProbe:
      probe: |
        httpGet:
          path: '/'
          port: http
      failureThreshold: 10
      periodSeconds: 10
    volumeMounts: {}
