---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.daemonset.template.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.daemonset.containers.image }}
        imagePullPolicy: {{ .Values.daemonset.containers.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.daemonset.containers.resources.requests.memory }}
            cpu: {{ .Values.daemonset.containers.resources.requests.cpu}}
            ephemeral-storage: {{ .Values.daemonset.containers.resources.requests.ephemeral_storage }}
          limits:
            memory: {{ .Values.daemonset.containers.resources.requests.memory }}
            cpu: {{ .Values.daemonset.containers.resources.requests.cpu }}
            ephemeral-storage: {{ .Values.daemonset.containers.resources.requests.ephemeral_storage }}
        ports:
        {{- range  $port := .Values.daemonset.containers.ports }}
        - name: {{ $port.name }}
          containerPort: {{ $port.containerPort }}
        {{- end }}
        readinessProbe: {{ .Values.daemonset.containers.readinessProbe.probe | nindent 10 }}
          initialDelaySeconds: {{ .Values.daemonset.containers.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.daemonset.containers.readinessProbe.periodSeconds }}
        livenessProbe: {{ .Values.daemonset.containers.livenessProbe.probe | nindent 10 }}
          initialDelaySeconds: {{ .Values.daemonset.containers.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.daemonset.containers.livenessProbe.periodSeconds }}
        startupProbe: {{ .Values.daemonset.containers.startupProbe.probe | nindent 10 }}
          failureThreshold: {{ .Values.daemonset.containers.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.daemonset.containers.startupProbe.periodSeconds }}
        volumeMounts:
        - name: {{ .Values.name }}
          mountPath: {{ .Values.daemonset.containers.volumeMounts.proxysql.mountPath }}
          subPath: {{ .Values.daemonset.containers.volumeMounts.proxysql.subPath }}
        env:
        {{- range $key, $value := .Values.daemonset.containers.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      volumes:
      - name: {{ .Values.name }}
        configMap:
          name: {{ .Values.daemonset.volumes.proxysql.configmap }}
